In [1]:
import requests
import bs4
import lxml
import pandas as pd

In [3]:
bat = pd.read_csv('Project CSV Files/Batting Data World Cup.csv')
m = pd.read_csv('Project CSV Files/Score Card World Cup.csv')
bowl = pd.read_csv('Project CSV Files/Bowling Data World Cup.csv')
player = pd.read_csv('Project CSV Files/dim_players.csv')

In [5]:
df1 = pd.DataFrame(bat)
df2 = pd.DataFrame(m)
df3 = pd.DataFrame(bowl)
df4 = pd.DataFrame(player)

In [ ]:
match_ids_dict = {}
for index, row in df2.iterrows():
    key = row['Team1'] + ' vs ' + row['Team2']
    match_ids_dict[key] = row['Score Card']

In [ ]:
df1['Match ID'] = df1['Match'].map(match_ids_dict)

In [6]:
df1.head(20)

,Match,Winning Team,Player,Runs,Balls,M,4s,6s,SR,Match ID
0,India vs Australia,Australia,Rohit Sharma,47,31,44,4,3,151.61,ODI # 4662
1,India vs Australia,Australia,Shubman Gill,4,7,21,0,0,57.14,ODI # 4662
2,India vs Australia,Australia,Virat Kohli,54,63,99,4,0,85.71,ODI # 4662
3,India vs Australia,Australia,Shreyas Iyer,4,3,3,1,0,133.33,ODI # 4662
4,India vs Australia,Australia,KL Rahul,66,107,133,1,0,61.68,ODI # 4662
5,India vs Australia,Australia,Ravindra Jadeja,9,22,33,0,0,40.90,ODI # 4662
6,India vs Australia,Australia,Suryakumar Yadav,18,28,57,1,0,64.28,ODI # 4662
7,India vs Australia,Australia,Mohammed Shami,6,10,9,1,0,60.00,ODI # 4662
8,India vs Australia,Australia,Jasprit Bumrah,1,3,5,0,0,33.33,ODI # 4662
9,India vs Australia,Australia,Kuldeep Yadav,10,18,28,0,0,55.55,ODI # 4662
10,India vs Australia,Australia,Mohammed Siraj,9,8,13,1,0,112.50,ODI # 4662
11,India vs Australia,Australia,David Warner,7,3,6,1,0,233.33,ODI # 4662
12,India vs Australia,Australia,Travis Head,137,120,166,15,4,114.16,ODI # 4662
13,India vs Australia,Australia,Mitchell Marsh,15,15,15,1,1,100.00,ODI # 4662
14,India vs Australia,Australia,Steven Smith,4,9,11,1,0,44.44,ODI # 4662
15,India vs Australia,Australia,Marnus Labuschagne,58,110,133,4,0,52.72,ODI # 4662
16,India vs Australia,Australia,Glenn Maxwell,2,1,1,0,0,200.00,ODI # 4662
17,Australia vs South Africa,Australia,Quinton de Kock,3,14,27,0,0,21.42,ODI # 4667
18,Australia vs South Africa,Australia,Temba Bavuma,0,4,5,0,0,0.00,ODI # 4667
19,Australia vs South Africa,Australia,Rassie van der Dussen,6,31,53,0,0,19.35,ODI # 4667

In [7]:
df2

,Team1,Team2,Winner,Margin,Ground,Match Date,Score Card
0,India,Australia,Australia,6 wickets,Ahmedabad,"Nov 19, 2023",ODI # 4705
1,Australia,South Africa,Australia,3 wickets,Eden Gardens,"Nov 16, 2023",ODI # 4704
2,India,New Zealand,India,70 runs,Wankhede,"Nov 15, 2023",ODI # 4703
3,India,Netherlands,India,160 runs,Bengaluru,"Nov 12, 2023",ODI # 4702
4,England,Pakistan,England,93 runs,Eden Gardens,"Nov 11, 2023",ODI # 4701
5,Australia,Bangladesh,Australia,8 wickets,Pune,"Nov 11, 2023",ODI # 4700
6,Afghanistan,South Africa,South Africa,5 wickets,Ahmedabad,"Nov 10, 2023",ODI # 4699
7,New Zealand,Sri Lanka,New Zealand,5 wickets,Bengaluru,"Nov 9, 2023",ODI # 4698
8,England,Netherlands,England,160 runs,Pune,"Nov 8, 2023",ODI # 4697
9,Afghanistan,Australia,Australia,3 wickets,Wankhede,"Nov 7, 2023",ODI # 4696
10,Bangladesh,Sri Lanka,Bangladesh,3 wickets,Delhi,"Nov 6, 2023",ODI # 4695
11,India,South Africa,India,243 runs,Eden Gardens,"Nov 5, 2023",ODI # 4694
12,Australia,England,Australia,33 runs,Ahmedabad,"Nov 4, 2023",ODI # 4693
13,New Zealand,Pakistan,Pakistan,21 runs,Bengaluru,"Nov 4, 2023",ODI # 4692
14,Afghanistan,Netherlands,Afghanistan,7 wickets,Lucknow,"Nov 3, 2023",ODI # 4691
15,India,Sri Lanka,India,302 runs,Wankhede,"Nov 2, 2023",ODI # 4690
16,New Zealand,South Africa,South Africa,190 runs,Pune,"Nov 1, 2023",ODI # 4689
17,Bangladesh,Pakistan,Pakistan,7 wickets,Eden Gardens,"Oct 31, 2023",ODI # 4688
18,Afghanistan,Sri Lanka,Afghanistan,7 wickets,Pune,"Oct 30, 2023",ODI # 4687
19,India,England,India,100 runs,Lucknow,"Oct 29, 2023",ODI # 4686
20,Bangladesh,Netherlands,Netherlands,87 runs,Eden Gardens,"Oct 28, 2023",ODI # 4685
21,Australia,New Zealand,Australia,5 runs,Dharamsala,"Oct 28, 2023",ODI # 4684
22,Pakistan,South Africa,South Africa,1 wicket,Chennai,"Oct 27, 2023",ODI # 4683
23,England,Sri Lanka,Sri Lanka,8 wickets,Bengaluru,"Oct 26, 2023",ODI # 4682
24,Australia,Netherlands,Australia,309 runs,Delhi,"Oct 25, 2023",ODI # 4681
25,Bangladesh,South Africa,South Africa,149 runs,Wankhede,"Oct 24, 2023",ODI # 4680
26,Afghanistan,Pakistan,Afghanistan,8 wickets,Chennai,"Oct 23, 2023",ODI # 4679
27,India,New Zealand,India,4 wickets,Dharamsala,"Oct 22, 2023",ODI # 4678
28,England,South Africa,South Africa,229 runs,Wankhede,"Oct 21, 2023",ODI # 4677
29,Netherlands,Sri Lanka,Sri Lanka,5 wickets,Lucknow,"Oct 21, 2023",ODI # 4676
30,Australia,Pakistan,Australia,62 runs,Bengaluru,"Oct 20, 2023",ODI # 4675
31,India,Bangladesh,India,7 wickets,Pune,"Oct 19, 2023",ODI # 4674
32,Afghanistan,New Zealand,New Zealand,149 runs,Chennai,"Oct 18, 2023",ODI # 4673
33,Netherlands,South Africa,Netherlands,38 runs,Dharamsala,"Oct 17, 2023",ODI # 4672
34,Australia,Sri Lanka,Australia,5 wickets,Lucknow,"Oct 16, 2023",ODI # 4671
35,Afghanistan,England,Afghanistan,69 runs,Delhi,"Oct 15, 2023",ODI # 4670
36,India,Pakistan,India,7 wickets,Ahmedabad,"Oct 14, 2023",ODI # 4669
37,Bangladesh,New Zealand,New Zealand,8 wickets,Chennai,"Oct 13, 2023",ODI # 4668
38,Australia,South Africa,South Africa,134 runs,Lucknow,"Oct 12, 2023",ODI # 4667
39,India,Afghanistan,India,8 wickets,Delhi,"Oct 11, 2023",ODI # 4666
40,Pakistan,Sri Lanka,Pakistan,6 wickets,Hyderabad,"Oct 10, 2023",ODI # 4665
41,Bangladesh,England,England,137 runs,Dharamsala,"Oct 10, 2023",ODI # 4664
42,Netherlands,New Zealand,New Zealand,99 runs,Hyderabad,"Oct 9, 2023",ODI # 4663
43,India,Australia,India,6 wickets,Chennai,"Oct 8, 2023",ODI # 4662
44,South Africa,Sri Lanka,South Africa,102 runs,Delhi,"Oct 7, 2023",ODI # 4661
45,Afghanistan,Bangladesh,Bangladesh,6 wickets,Dharamsala,"Oct 7, 2023",ODI # 4660
46,Netherlands,Pakistan,Pakistan,81 runs,Hyderabad,"Oct 6, 2023",ODI # 4659
47,England,New Zealand,New Zealand,9 wickets,Ahmedabad,"Oct 5, 2023",ODI # 4658

In [9]:
df3.head(20)

,Match,Winning Team,Player,Overs,Runs,Wickets,Econ,Wide,NB,Match ID
0,India vs Australia,Australia,Mitchell Starc,10.0,55,3,5.50,3,0,ODI # 4662
1,India vs Australia,Australia,Josh Hazlewood,10.0,60,2,6.00,1,0,ODI # 4662
2,India vs Australia,Australia,Glenn Maxwell,6.0,35,1,5.83,0,0,ODI # 4662
3,India vs Australia,Australia,Pat Cummins,10.0,34,2,3.40,2,0,ODI # 4662
4,India vs Australia,Australia,Adam Zampa,10.0,44,1,4.40,1,0,ODI # 4662
5,India vs Australia,Australia,Mitchell Marsh,2.0,5,0,2.50,0,0,ODI # 4662
6,India vs Australia,Australia,Travis Head,2.0,4,0,2.00,0,0,ODI # 4662
7,India vs Australia,Australia,Jasprit Bumrah,9.0,43,2,4.77,0,0,ODI # 4662
8,India vs Australia,Australia,Mohammed Shami,7.0,47,1,6.71,3,0,ODI # 4662
9,India vs Australia,Australia,Ravindra Jadeja,10.0,43,0,4.30,1,0,ODI # 4662
10,India vs Australia,Australia,Kuldeep Yadav,10.0,56,0,5.60,0,0,ODI # 4662
11,India vs Australia,Australia,Mohammed Siraj,7.0,45,1,6.42,0,0,ODI # 4662
12,Australia vs South Africa,Australia,Mitchell Starc,10.0,34,3,3.40,4,0,ODI # 4667
13,Australia vs South Africa,Australia,Josh Hazlewood,8.0,12,2,1.50,0,0,ODI # 4667
14,Australia vs South Africa,Australia,Pat Cummins,9.4,51,3,5.27,2,0,ODI # 4667
15,Australia vs South Africa,Australia,Adam Zampa,7.0,55,0,7.85,0,0,ODI # 4667
16,Australia vs South Africa,Australia,Glenn Maxwell,10.0,35,0,3.50,0,0,ODI # 4667
17,Australia vs South Africa,Australia,Travis Head,5.0,21,2,4.20,1,0,ODI # 4667
18,Australia vs South Africa,Australia,Marco Jansen,4.2,35,0,8.07,4,0,ODI # 4667
19,Australia vs South Africa,Australia,Kagiso Rabada,6.0,41,1,6.83,1,1,ODI # 4667

In [10]:
df4

,name,team,image,battingStyle,bowlingStyle,playingRole,description
0,Najmul Hossain Shanto,Bangladesh,NaN,Left hand Bat,Right arm Offbreak,Top order Batter,Nazmul Hossain Shanto emerged from an unusual ...
1,Soumya Sarkar,Bangladesh,NaN,Left hand Bat,Right arm Medium fast,Middle order Batter,"A rarity among Bangladesh allrounders, top-ord..."
2,Litton Das,Bangladesh,NaN,Right hand Bat,NaN,Wicketkeeper Batter,Liton Das is the first wicketkeeper-batsman in...
3,Shakib Al Hasan(c),Bangladesh,NaN,Left hand Bat,Slow Left arm Orthodox,Allrounder,When the annals of Bangladesh cricket are sift...
4,Afif Hossain,Bangladesh,NaN,Left hand Bat,Right arm Offbreak,Allrounder,Bangladesh left-hander Afif Hossain made his T...
...,...,...,...,...,...,...,...
214,Shoriful Islam,Bangladesh,NaN,Left hand Bat,Left arm Medium fast,Bowler,"At 6ft three inches, Shoriful Islam became a l..."
215,Phil Salt,England,NaN,Right hand Bat,Right arm Offbreak,Wicketkeeper Batter,Phil Salt's fearless ball-striking at the top ...
216,Ashton Agar,Australia,NaN,Left hand Bat,Slow Left arm Orthodox,Bowler,Ashton Agar initially turned almost as many he...
217,Heinrich Klaasen,South Africa,NaN,Right hand Bat,Right arm Offbreak,Wicketkeeper Batter,"A clean-hitting, wicketkeeper batsman, Heinric..."
218,Timm van der Gugten,Netherlands,NaN,Right hand Bat,Right arm Fast medium,Bowler,"Timm van der Gugten, born in Sydney, made his ..."

In [13]:
match_name_dict = {}
for index, row in df1.iterrows():
    match_name_dict['Player'] = row['Match ID']

In [14]:
df1['Player'] = df4['name'].map(match_ids_dict)

NameError: name 'match_ids_dict' is not defined